apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "project-1"
  namespace: "backend"
  labels:
    app: "k8s-node"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "k8s-node"
  template:
    metadata:
      labels:
        app: "k8s-node"
    spec:
      containers:
        - name: "project-11"
          image: "195394092895.dkr.ecr.eu-west-1.amazonaws.com/project:newbuildNumber"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
